In [1]:
import numpy as np
np.__version__

'2.4.2'

In [8]:
ls=[[[1,2,3]]]
arr=np.array(ls)
type(arr)

numpy.ndarray

In [9]:
arr.ndim

3

In [10]:
arr.size

3

In [11]:
arr.shape

(1, 1, 3)

In [17]:
ls=[[1,2,3,9.78,4.67]]
arr1=np.array(ls)
arr1

array([[1.  , 2.  , 3.  , 9.78, 4.67]])

In [18]:
np.array([12,43,23,2.5])

array([12. , 43. , 23. ,  2.5])

In [19]:
np.array([12,43,23,2.5+2j])

array([12. +0.j, 43. +0.j, 23. +0.j,  2.5+2.j])

In [24]:
np.array([12,43,23,2.5],dtype='int')

array([12, 43, 23,  2])

In [25]:
np.array([12,43,23,2.5],dtype='complex')

array([12. +0.j, 43. +0.j, 23. +0.j,  2.5+0.j])

In [27]:
new_arr=np.array([[12,43,23],
         [2,43,23],
         [120,43,23]])
new_arr

array([[ 12,  43,  23],
       [  2,  43,  23],
       [120,  43,  23]])

In [29]:
new_arr.ndim

2

In [30]:
np.array([[[[]]]]).ndim

4

In [33]:
new_arr=np.array([[12,43,23],
         [2,43,23],
         [120,43,np.nan]])
new_arr

array([[ 12.,  43.,  23.],
       [  2.,  43.,  23.],
       [120.,  43.,  nan]])

In [34]:
new_arr=np.array([[12,43,23],
         [2,43,23],
         [120,43,None]])
new_arr

array([[12, 43, 23],
       [2, 43, 23],
       [120, 43, None]], dtype=object)

In [36]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
np.arange(1.5,11.5)

array([ 1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5])

In [40]:
np.arange(1.5,11.5,2)

array([1.5, 3.5, 5.5, 7.5, 9.5])

In [43]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
arr.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [50]:
arr=np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]]])
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [51]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [54]:
np.ones([2,3],dtype='int')

array([[1, 1, 1],
       [1, 1, 1]])

In [56]:
np.ones([2,3,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [57]:
np.zeros([2,3,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [58]:
np.full(10,7)

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [59]:
np.full([2,3],5)

array([[5, 5, 5],
       [5, 5, 5]])

In [60]:
np.full([2,3],[7,8,9])

array([[7, 8, 9],
       [7, 8, 9]])

In [63]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.randint(1,100,5) #int will generate only interger value

array([21, 93, 45, 23, 58], dtype=int32)

In [81]:
np.random.randint(1,101)

86

In [93]:
np.random.randint(3,200,20)

array([104,  88, 100, 171,  95,  47,  67, 121, 193,  63, 102, 154,  89,
       132,  12, 122, 182, 161, 137, 175], dtype=int32)

In [94]:
np.random.randint(100,200,[3,4])

array([[146, 110, 101, 167],
       [133, 172, 148, 127],
       [118, 115, 130, 166]], dtype=int32)

In [95]:
np.random.rand(5)

array([0.91851757, 0.61787082, 0.4072873 , 0.86023284, 0.84978107])

In [ ]:
np.random.rand(1,10,5) # used to show uniform distribution

array([[[0.8998949 , 0.20565574, 0.49699623, 0.45243667, 0.75563756],
        [0.50786093, 0.78277404, 0.26390649, 0.81994838, 0.6184582 ],
        [0.85695044, 0.11355602, 0.35726183, 0.18031036, 0.9959269 ],
        [0.29687842, 0.02119784, 0.96797839, 0.47644358, 0.00806064],
        [0.81644916, 0.87471904, 0.11406838, 0.44083519, 0.90515589],
        [0.43853457, 0.95655196, 0.28698978, 0.75342076, 0.66644129],
        [0.23603622, 0.65729896, 0.01380218, 0.38011228, 0.34466601],
        [0.61840167, 0.37472649, 0.83279458, 0.13029942, 0.16727621],
        [0.1461686 , 0.36605082, 0.53114776, 0.69425392, 0.92308109],
        [0.55189759, 0.54115625, 0.35921311, 0.05281546, 0.33651743]]])

In [97]:
np.random.randn(5)

array([-0.21546058,  0.01532384, -0.0901576 ,  0.63418335, -0.86287604])

In [101]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [104]:
np.linspace(2,5,retstep=True)

(array([2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796,
        2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041,
        2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286,
        2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531,
        3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776,
        3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ,
        3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265,
        4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ,
        4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755,
        4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ]),
 np.float64(0.061224489795918366))

In [107]:
arr=np.arange(1,11).reshape([2,5])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

#### **Copy and View**

In [ ]:
new_arr=arr.view() # It will pass the reference
new_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [110]:
arr[0][0]=100
arr

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [111]:
new_arr

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [112]:
new_arr_copy=arr.copy()
new_arr_copy

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [113]:
arr[0][0]=1000

In [114]:
new_arr_copy

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [115]:
new_arr_copy.T

array([[100,   6],
       [  2,   7],
       [  3,   8],
       [  4,   9],
       [  5,  10]])

In [116]:
new_arr.T

array([[1000,    6],
       [   2,    7],
       [   3,    8],
       [   4,    9],
       [   5,   10]])